REGION_NAMES = ["US-CAL-CISO", "US-MIDA-PJM", "US-MIDW-MISO", "US-TEX-ERCO"]
REGION_LOCATIONS = {
    "US-CAL-CISO": (-120, 30),
    "US-MIDA-PJM": (-75, 40),
    "US-MIDW-MISO": (-80, 40),
    "US-TEX-ERCO": (-95, 30),
}
REGION_OFFSETS = {"US-CAL-CISO": 0, "US-MIDA-PJM": 6, "US-MIDW-MISO": 2, "US-TEX-ERCO": 2}
TASK_LIFETIME_MEAN = 12
TASK_LIFETIME_STD = 4
